###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: prism.actions.statefulset
#  namespace: prism
  labels:
data:
  url-actions: |
    [
      { 
        "name":"detail", 
        "text":"StatefulSet detail", 
        "description":"StatefulSet detail", 
        "url-pattern":"${builtin.icp-console-url}/workloads/statefulsets/${resource.$.metadata.namespace}/${resource.$.metadata.name}",
        "open-window": "current", 
        "menu-item": "false" 
      }
    ]