###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion:  v1
kind: ConfigMap
metadata: 
  name: prism.actions.watson-tone-analyzer
  namespace: prism
  labels:
data:
  url-actions: | 
      [
        {  
          "name": "Service Instance", 
          "text": "Service Instance",
          "description": "View service instance in IBM Cloud", 
          "url-pattern": "${resource.$.metadata.annotations['prism.platform.console-url']}",
          "open-window": "tab"
        }
      ] 
