apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: default
    kubebuilder.k8s.io: 0.1.10
  name: watson-tone-analyzers.prism.io
spec:
  group: prism.io
  names:
    kind: Watson-Tone-Analyzer
    plural: watson-tone-analyzers
    singular: watson-tone-analyzer
    shortNames: 
      - ai-tone
      - watson-tone
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        status:
          properties:
            observedGeneration:
              type: int64
          type: string 
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []