apiVersion: v1
kind: PersistentVolume
metadata:
  name: db2-storage
  labels:
    assign-to: "data-stor"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  hostPath:
    path: /var/db2_home