apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2-claim
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 20Gi
  volumeName: db2-storage
  storageClassName: nfs-client