apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJqZWZmcmV5YnVuYWdhbiIsInBhc3N3b3JkIjoiTmFwYWthaCFyYXA4NSIsImVtYWlsIjoiamVmZnJleS5idW5hZ2FuQGhjbC5jb20iLCJhdXRoIjoiYW1WbVpuSmxlV0oxYm1GbllXNDZUbUZ3WVd0aGFDRnlZWEE0TlE9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
